### ISSUE TITLE
VirtualBot: Error Handling when Disconnecting a Bot from Basestation

### ISSUE THREAD

**Issue by chynu** [cornell-cup/cs-minibot#78]
https://github.com/cornell-cup/cs-minibot/blob/76ea05952c9e7b962d05c6be5a6fcae034397b39/basestation/bot/virtualbot/virtual_bot.py#L125

Add error handling for this. There is no else clause, so when the bot disconnects the basestation throws an error.

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/celinechoo/Code/cs-minibot/basestation/bot/virtualbot/virtual_bot.py", line 104, in run
    self.__tcp_parse_incoming(msg)
  File "/Users/celinechoo/Code/cs-minibot/basestation/bot/virtualbot/virtual_bot.py", line 122, in __tcp_parse_incoming
    start = data.index("<<<<")
ValueError: substring not found

```

**Comment by anmolkabra** [comment]
I don't think that adding an else clause will help here. I thought that index would return a -1 if the substring was not found, but it's raising a ValueError. I will enclose this in a try-catch block to get this error. Do we want the basestation to do something when the bot disconnects? (That will go in the catch block)

**Comment by anmolkabra** [comment]
We can use `data.find(">>>>")` which should return -1 and not throw an error. (See the python3 doc https://docs.python.org/3/library/stdtypes.html). Which do you like?
